# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'After_Splash.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calculator(object):
    def setupUi(self, Calculator):
        Calculator.setObjectName("Calculator")
        Calculator.resize(440, 700)
        Calculator.setMinimumSize(QtCore.QSize(440, 700))
        Calculator.setMaximumSize(QtCore.QSize(440, 700))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/newPrefix/logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Calculator.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(Calculator)
        self.centralwidget.setObjectName("centralwidget")
        self.background = QtWidgets.QLabel(self.centralwidget)
        self.background.setGeometry(QtCore.QRect(0, 0, 440, 700))
        self.background.setText("")
        self.background.setPixmap(QtGui.QPixmap(":/newPrefix/background.png"))
        self.background.setScaledContents(True)
        self.background.setObjectName("background")
        self.Answer = QtWidgets.QLineEdit(self.centralwidget)
        self.Answer.setGeometry(QtCore.QRect(20, 110, 401, 71))
        font = QtGui.QFont()
        font.setFamily("Leelawadee")
        font.setPointSize(21)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.Answer.setFont(font)
        self.Answer.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.Answer.setObjectName("Answer")
        self.decimal = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.decimal.setGeometry(QtCore.QRect(10, 610, 81, 71))
        self.decimal.setFocusPolicy(QtCore.Qt.NoFocus)
        self.decimal.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/newPrefix/dummy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.decimal.setIcon(icon1)
        self.decimal.setObjectName("decimal")
        self.zero = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.zero.setGeometry(QtCore.QRect(130, 610, 81, 71))
        self.zero.setFocusPolicy(QtCore.Qt.NoFocus)
        self.zero.setText("")
        self.zero.setIcon(icon1)
        self.zero.setObjectName("zero")
        self.equal = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.equal.setGeometry(QtCore.QRect(250, 610, 81, 71))
        self.equal.setFocusPolicy(QtCore.Qt.NoFocus)
        self.equal.setText("")
        self.equal.setIcon(icon1)
        self.equal.setObjectName("equal")
        self.addition = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.addition.setGeometry(QtCore.QRect(350, 610, 81, 71))
        self.addition.setFocusPolicy(QtCore.Qt.NoFocus)
        self.addition.setText("")
        self.addition.setIcon(icon1)
        self.addition.setObjectName("addition")
        self.subtraction = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.subtraction.setGeometry(QtCore.QRect(350, 510, 81, 71))
        self.subtraction.setFocusPolicy(QtCore.Qt.NoFocus)
        self.subtraction.setText("")
        self.subtraction.setIcon(icon1)
        self.subtraction.setObjectName("subtraction")
        self.division = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.division.setGeometry(QtCore.QRect(350, 420, 81, 71))
        self.division.setFocusPolicy(QtCore.Qt.NoFocus)
        self.division.setText("")
        self.division.setIcon(icon1)
        self.division.setObjectName("division")
        self.multiplication = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.multiplication.setGeometry(QtCore.QRect(350, 320, 81, 71))
        self.multiplication.setFocusPolicy(QtCore.Qt.NoFocus)
        self.multiplication.setText("")
        self.multiplication.setIcon(icon1)
        self.multiplication.setObjectName("multiplication")
        self.three = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.three.setGeometry(QtCore.QRect(250, 510, 81, 71))
        self.three.setFocusPolicy(QtCore.Qt.NoFocus)
        self.three.setText("")
        self.three.setIcon(icon1)
        self.three.setObjectName("three")
        self.two = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.two.setGeometry(QtCore.QRect(130, 510, 81, 71))
        self.two.setFocusPolicy(QtCore.Qt.NoFocus)
        self.two.setText("")
        self.two.setIcon(icon1)
        self.two.setObjectName("two")
        self.one = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.one.setGeometry(QtCore.QRect(10, 510, 81, 71))
        self.one.setFocusPolicy(QtCore.Qt.NoFocus)
        self.one.setText("")
        self.one.setIcon(icon1)
        self.one.setObjectName("one")
        self.six = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.six.setGeometry(QtCore.QRect(250, 420, 81, 71))
        self.six.setFocusPolicy(QtCore.Qt.NoFocus)
        self.six.setText("")
        self.six.setIcon(icon1)
        self.six.setObjectName("six")
        self.five = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.five.setGeometry(QtCore.QRect(130, 420, 81, 71))
        self.five.setFocusPolicy(QtCore.Qt.NoFocus)
        self.five.setText("")
        self.five.setIcon(icon1)
        self.five.setObjectName("five")
        self.four = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.four.setGeometry(QtCore.QRect(10, 420, 81, 71))
        self.four.setFocusPolicy(QtCore.Qt.NoFocus)
        self.four.setText("")
        self.four.setIcon(icon1)
        self.four.setObjectName("four")
        self.nine = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.nine.setGeometry(QtCore.QRect(250, 320, 81, 71))
        self.nine.setFocusPolicy(QtCore.Qt.NoFocus)
        self.nine.setText("")
        self.nine.setIcon(icon1)
        self.nine.setObjectName("nine")
        self.eight = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.eight.setGeometry(QtCore.QRect(130, 320, 81, 71))
        self.eight.setFocusPolicy(QtCore.Qt.NoFocus)
        self.eight.setText("")
        self.eight.setIcon(icon1)
        self.eight.setObjectName("eight")
        self.seven = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.seven.setGeometry(QtCore.QRect(10, 320, 81, 71))
        self.seven.setFocusPolicy(QtCore.Qt.NoFocus)
        self.seven.setText("")
        self.seven.setIcon(icon1)
        self.seven.setObjectName("seven")
        self.bracket = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.bracket.setGeometry(QtCore.QRect(10, 220, 81, 71))
        self.bracket.setFocusPolicy(QtCore.Qt.NoFocus)
        self.bracket.setText("")
        self.bracket.setIcon(icon1)
        self.bracket.setObjectName("bracket")
        self.root = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.root.setGeometry(QtCore.QRect(130, 220, 81, 71))
        self.root.setFocusPolicy(QtCore.Qt.NoFocus)
        self.root.setText("")
        self.root.setIcon(icon1)
        self.root.setObjectName("root")
        self.clear = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.clear.setGeometry(QtCore.QRect(250, 220, 181, 71))
        self.clear.setFocusPolicy(QtCore.Qt.NoFocus)
        self.clear.setText("")
        self.clear.setIcon(icon1)
        self.clear.setObjectName("clear")
        Calculator.setCentralWidget(self.centralwidget)

        self.retranslateUi(Calculator)
        QtCore.QMetaObject.connectSlotsByName(Calculator)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.Answer.setPlaceholderText(_translate("Calculator", "Calculation Goes Here"))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Calculator = QtWidgets.QMainWindow()
    ui = Ui_Calculator()
    ui.setupUi(Calculator)
    Calculator.show()
    sys.exit(app.exec_())

